### Health check
GET http://localhost:4000/health

### List Stores
GET http://localhost:4000/api/v1/stores HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjRXSUxUSmh1cGVlY3BPZENyMGJ2TiJ9.eyJpc3MiOiJodHRwczovL2Rldi1raDQ4eWt6OHY0czI0bmQxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNTQ1NTAzODY2NTczMTY4ODM4OCIsImF1ZCI6WyJzYWxhdHktYXBpIiwiaHR0cHM6Ly9kZXYta2g0OHlrejh2NHMyNG5kMS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzQ5NjM2NjU0LCJleHAiOjE3NDk3MjMwNTQsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiIzZFM5Rkltc0hPbDBXODBlTG1Va3pxRWdyZGVPZzY0ciJ9.M6G08Ms_bGKr4gWI0Lbry2oIcI5mlQKOnFaFlnToVJcp0xcagpgrbrp1NFBPqChx6OEk2W7s3v9ySZvdeFZFFP1H2OYvvjqQc-UUHDoIsrAAd4yImHfgQ0JWHXNpoWXJctlcRPvRJqaqwv6kT7pIDyHHIUvCsfwWhTaZRpdhNvZgn4_16Mq0rrOBZXFS61q9rU8g13rYS9pyf9KZsUsVdzBfH84WPlMqbwhBkxi40NfykEsdAbf7ztm3K9Fhng2hfIeeuutf2T8wac9ldcfWNPfDDYhwP3VQEeE2kxKOmfvrTNhsiPKGP4wb6H16hJQ-X9hIYlV1Pw1GCMJnfC1WpQ